# Generated by Django 4.2.11 on 2025-05-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
