# Generated by Django 4.2.11 on 2025-05-26 22:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/hoppe/Desktop/projects/trustrevs/trustforum270525/forum/protected_files'), upload_to=''),
        ),
    ]
