# Generated by Django 5.1.6 on 2025-05-29 20:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_file_status_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='file_images/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\simon\\Desktop\\trustforum270525_1 - copia\\forum\\protected_files'), upload_to=''),
        ),
    ]
